image: $BIN_REPO_URL_DOCKER/srsng/helm-jfrog:latest
stages:
  - deploy

deploy:
  stage: deploy
  script:
    - apk add --no-cache aws-cli
    - aws --version
    - export AWS_ACCESS_KEY_ID="AKIAZNJEO32D3KPNPZLG"
    - export AWS_SECRET_ACCESS_KEY="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"
    - export AWS_DEFAULT_REGION=ap-southeast-1
    - aws s3 ls s3://ap-southeast-1-demo-counter-s3-bucket/projects/counter/index.html
    - aws s3 cp counter.html s3://ap-southeast-1-demo-counter-s3-bucket/projects/counter/index.html
    - aws s3 cp default.conf s3://ap-southeast-1-demo-counter-s3-bucket/projects/counter/default.conf
    - aws s3 ls s3://ap-southeast-1-demo-counter-s3-bucket/projects/counter/index.html
    - sleep 10
    #- aws autoscaling start-instance-refresh --cli-input-json file://config.json